package com.zibilal.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.zibilal.dao.Company;
import com.zibilal.dao.Client;
import com.zibilal.dao.Order;

import com.zibilal.dao.CompanyDao;
import com.zibilal.dao.ClientDao;
import com.zibilal.dao.OrderDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig companyDaoConfig;
    private final DaoConfig clientDaoConfig;
    private final DaoConfig orderDaoConfig;

    private final CompanyDao companyDao;
    private final ClientDao clientDao;
    private final OrderDao orderDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        companyDaoConfig = daoConfigMap.get(CompanyDao.class).clone();
        companyDaoConfig.initIdentityScope(type);

        clientDaoConfig = daoConfigMap.get(ClientDao.class).clone();
        clientDaoConfig.initIdentityScope(type);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        companyDao = new CompanyDao(companyDaoConfig, this);
        clientDao = new ClientDao(clientDaoConfig, this);
        orderDao = new OrderDao(orderDaoConfig, this);

        registerDao(Company.class, companyDao);
        registerDao(Client.class, clientDao);
        registerDao(Order.class, orderDao);
    }
    
    public void clear() {
        companyDaoConfig.getIdentityScope().clear();
        clientDaoConfig.getIdentityScope().clear();
        orderDaoConfig.getIdentityScope().clear();
    }

    public CompanyDao getCompanyDao() {
        return companyDao;
    }

    public ClientDao getClientDao() {
        return clientDao;
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

}
